name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all Git history so that Changesets can generate changelogs with the correct commits

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # release calls changeset publish which runs the prepublishOnly scripts in each package beforehand to test and build 
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Notify if a publish happens
      #   if: steps.changesets.outputs.published == 'true'
      #   run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"